import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const source = readFileSync(new URL('../InsightsView.tsx', import.meta.url), 'utf8')

describe('Insights inference policy', () => {
  it('keeps technique-confounded swim EF out of inferential views', () => {
    const perfOptions = source.match(/const PERFS = \[[\s\S]*?\n\]/)?.[0] ?? ''
    const perfAccumulator = source.match(/const perfAcc:[\s\S]*?\n[ ]{4}}/)?.[0] ?? ''

    expect(perfOptions).not.toContain("key: 'ef'")
    expect(perfAccumulator).not.toContain('ef: new Map()')
    expect(source).toContain("model.name !== 'ef_on_sleep_dlm'")
    expect(source).toContain("candidate.outcome !== 'ef'")
    expect(source).toContain("correlation.var_y !== 'ef'")
    expect(source).toContain('insightWindowStart(selected.computed_at, timezone)')
    expect(source).toContain("{ key: 'trimp_total', label: 'Workout-day load' }")
    expect(source).toContain("selected.var_y === 'trimp_total'")
    expect(source).toContain('Load relationships are waiting for the next metrics recompute')
    expect(source).not.toContain('finderDiagnostics.candidate_count ?? finderCandidates.length')
  })

  it('surfaces the expanded daily and workout-context inference contracts', () => {
    expect(source).toContain("key: 'sleep_shortfall'")
    expect(source).toContain("key: 'sleep_awake_fraction'")
    expect(source).toContain("key: 'respiratory_rate_dev'")
    expect(source).toContain("key: 'steps_prior'")
    expect(source).toContain("key: 'flights_prior'")
    expect(source).toContain("key: 'weight_7d_slope'")
    expect(source).toContain("model.name === 'workout_context_finder'")
    expect(source).toContain("model.name !== 'workout_context_finder'")
    expect(source).toContain('diagnostics?.model_version === family.expectedVersion')
    expect(source).toContain('waitingForExpandedRecompute')
    expect(source).toContain('Block-bootstrap stability')
    expect(source).toContain('Seven-night persistence')
    expect(source).toContain('Null calibration:')
    expect(source).toContain('insightAxis(')
    expect(source).toMatch(/key: 'daily'[\s\S]*?expectedVersion: 4/)
    expect(source).toMatch(/key: 'workout'[\s\S]*?expectedVersion: 7/)
    expect(source).toContain('candidate.n_days')
    expect(source).toContain('sessions / dates')
    expect(source).toContain('60 distinct workout dates')
    expect(source).toContain('hrCoverage >= 0.9')
    expect(source).toContain('sessions with ≥90% HR coverage')
    expect(source).toContain("const FINALIZED_DAILY_DRIVERS = new Set(['rhr_dev', 'hrv_dev'])")
    expect(source).toContain('correlation.lag_days === 0')
    expect(source).toContain('FINALIZED_DAILY_DRIVERS.has(correlation.var_x)')
    expect(source).toContain("candidate.direction === 'prior-day-to-workout'")
    expect(source).toContain('finalized daily aggregate predates the workout')
    expect(source).toContain("FINALIZED_DAILY_DRIVERS.has(candidate.outcome ?? '')")
    expect(source).toContain('Same-date association with a finalized daily aggregate')
    expect(source).toContain("title: 'Daily physiology'")
    expect(source).toContain("detail: 'Prior-day behavior, sleep, and finalized daily aggregates'")
    expect(source).toContain("label: 'Physiology context'")
    expect(source).toContain("detail: 'finalized RHR or HRV days'")
    expect(source).toContain("candidate.direction === 'pre-workout-state'")
    expect(source).toContain('accumulated load, and workout timing')
    expect(source).toContain("put('flights', m.date, m.flights_climbed)")
    expect(source).toContain("put('flights_prior', r.date")
    expect(source).toContain("correlation.var_x === 'flights_prior'")
  })
})
